/**
 * SallyNeuralCompositor.js
 * 
 * Regional Lower-Face Neural Compositor for Sally IP.
 * Composites the neural lower-face patch (mouth, lips, jaw) generated by the Web Worker
 * onto the base real-human Sally high-definition stream using GPU canvas compositing
 * and an elliptical feather blending mask.
 * 
 * Debug Modes:
 * - RAW NEURAL ONLY: Displays ONLY the raw 96x96 neural output enlarged without any blending.
 * - SPLIT COMPARISON (Ctrl+Shift+N): Displays 3-panel side-by-side:
 *     [ Base Image | Raw Neural Output | Final Composited Frame ]
 */

import { SALLY_16_9_STAGE_CONFIG, createSallyBlendingMask } from './sallyIdentity.js';
import { VOICE_STATES } from '../types.js';

export class SallyNeuralCompositor {
  constructor(canvasElement, options = {}) {
    this.canvas = canvasElement;
    this.ctx = canvasElement?.getContext?.('2d', { alpha: false, desynchronized: true });
    this.stageConfig = SALLY_16_9_STAGE_CONFIG;
    this.patchGeometry = this.stageConfig.cropBox; // 112x112 at (642, 279)

    // Pre-create blending mask for 112x112
    this.mask = createSallyBlendingMask(this.patchGeometry.width, this.patchGeometry.height);

    // Intermediate buffer for 112x112 alpha feathering
    this.patchBufferCanvas = null;
    this.patchBufferCtx = null;

    // Intermediate 96x96 buffer for ONNX tensor conversion
    this.rawNeuralCanvas = null;
    this.rawNeuralCtx = null;
    this.initBuffers();

    // Preload widescreen 16:9 stage image
    this.stageImage = null;
    if (typeof Image !== 'undefined') {
      this.stageImage = new Image();
      this.stageImage.src = this.stageConfig.imagePath;
    }

    // Visual & Debug state
    this.state = VOICE_STATES.IDLE;
    this.showRawNeuralOnly = false;
    this.showSplitComparison = false;
    this.cachedReferencePatchRgba = null;
    this.lastInferenceMs = 0;
    this.currentFrameIndex = 0;
    this.neuralFps = 25.0;
    this.avDeltaMs = 0;
    this.provider = 'WebGPU';

    // Idle motion state
    this.blinkTimer = 0;
  }

  initBuffers() {
    if (typeof document !== 'undefined') {
      // 112x112 composite buffer
      this.patchBufferCanvas = document.createElement('canvas');
      this.patchBufferCanvas.width = this.patchGeometry.width;
      this.patchBufferCanvas.height = this.patchGeometry.height;
      this.patchBufferCtx = this.patchBufferCanvas.getContext('2d');

      // 96x96 raw neural buffer
      this.rawNeuralCanvas = document.createElement('canvas');
      this.rawNeuralCanvas.width = 96;
      this.rawNeuralCanvas.height = 96;
      this.rawNeuralCtx = this.rawNeuralCanvas.getContext('2d');
    }
  }

  setState(newState) {
    this.state = newState;
  }

  extractReferencePatch(sourceElement) {
    const isLoaded = (el) => el && ((el.videoWidth && el.videoWidth > 0) || (el.complete && el.naturalWidth > 0));
    const el = isLoaded(sourceElement)
      ? sourceElement
      : (isLoaded(this.stageImage) ? this.stageImage : null);
    if (!el || !this.rawNeuralCtx) return null;

    const { x, y, width, height } = this.patchGeometry;
    // Draw 112x112 mouth crop into 96x96 ONNX tensor buffer
    this.rawNeuralCtx.drawImage(el, x, y, width, height, 0, 0, 96, 96);
    const imageData = this.rawNeuralCtx.getImageData(0, 0, 96, 96);
    this.cachedReferencePatchRgba = imageData.data;
    return this.cachedReferencePatchRgba;
  }

  renderFrame(baseElement, neuralPatch = null, meta = {}) {
    if (!this.canvas || !this.ctx) return;

    const cW = this.canvas.width;
    const cH = this.canvas.height;

    // Always clear canvas before rendering to guarantee clean frame and prevent artifacts
    this.ctx.clearRect(0, 0, cW, cH);

    const isLoaded = (el) => el && ((el.videoWidth && el.videoWidth > 0) || (el.complete && el.naturalWidth > 0));
    const sourceEl = isLoaded(baseElement)
      ? baseElement
      : (isLoaded(this.stageImage) ? this.stageImage : null);

    if (meta.inferenceMs) this.lastInferenceMs = meta.inferenceMs;
    if (meta.frameIndex) this.currentFrameIndex = meta.frameIndex;
    if (meta.fps) this.neuralFps = meta.fps;
    if (meta.avDeltaMs !== undefined) this.avDeltaMs = meta.avDeltaMs;
    if (meta.provider) this.provider = meta.provider;

    const nowSec = (typeof performance !== 'undefined' ? performance.now() : Date.now()) * 0.001;

    // -------------------------------------------------------------
    // DEBUG MODE 1: RAW NEURAL OUTPUT ONLY
    // Strictly model output only: no base portrait, no compositor,
    // no feather mask, no CSS animation, no procedural mouth.
    // -------------------------------------------------------------
    if (this.showRawNeuralOnly) {
      this.ctx.fillStyle = '#050811';
      this.ctx.fillRect(0, 0, cW, cH);

      if (neuralPatch && this.rawNeuralCtx) {
        if (neuralPatch instanceof ImageData) {
          this.rawNeuralCtx.putImageData(neuralPatch, 0, 0);
        } else {
          this.rawNeuralCtx.drawImage(neuralPatch, 0, 0, 96, 96);
        }

        const renderSize = Math.min(cW, cH) * 0.65;
        const offX = (cW - renderSize) / 2;
        const offY = (cH - renderSize) / 2 - 20;

        this.ctx.imageSmoothingEnabled = false; // Nearest-neighbor to view exact neural pixels
        this.ctx.drawImage(this.rawNeuralCanvas, offX, offY, renderSize, renderSize);

        this.drawCenteredText('RAW NEURAL OUTPUT ONLY (Wav2Lip 96x96 RGB Tensor)', cW / 2, offY - 24, '#38bdf8', 'bold 15px monospace');
        this.drawCenteredText('No base portrait  |  No compositor  |  No feather mask  |  No procedural mouth', cW / 2, offY + renderSize + 30, '#94a3b8', '12px monospace');
      } else {
        // Explicitly display when neural model is not producing frames
        this.drawCenteredText('NEURAL MODEL NOT RUNNING', cW / 2, cH / 2 - 10, '#f87171', 'bold 20px monospace');
        this.drawCenteredText('Awaiting speech audio inference... (Procedural fallback is DISABLED)', cW / 2, cH / 2 + 20, '#94a3b8', '13px monospace');
      }

      // Bottom telemetry bar
      this.drawTelemetryBar(cW, cH);
      return;
    }

    // -------------------------------------------------------------
    // DEBUG MODE 2: SPLIT COMPARISON (Ctrl+Shift+N)
    // Three Panels: [ SOURCE FRAME | RAW NEURAL OUTPUT — WEBGPU | FINAL COMPOSITE ]
    // -------------------------------------------------------------
    if (this.showSplitComparison) {
      this.ctx.fillStyle = '#030712';
      this.ctx.fillRect(0, 0, cW, cH);

      const panelW = Math.floor(cW / 3);
      const contentH = cH - 48; // Leave 48px for bottom telemetry bar

      // PANEL 1: SOURCE FRAME
      if (sourceEl) {
        const aspect = 1376 / 768;
        const drawH = Math.floor(panelW / aspect);
        const offY = Math.floor((contentH - drawH) / 2);
        this.ctx.drawImage(sourceEl, 0, offY, panelW, drawH);
      }
      this.drawPanelHeader('SOURCE FRAME', 16, 26, '#94a3b8');

      // PANEL 2: RAW NEURAL OUTPUT — WEBGPU
      const p2X = panelW;
      this.ctx.fillStyle = '#050811';
      this.ctx.fillRect(p2X, 0, panelW, contentH);

      if (neuralPatch && this.rawNeuralCtx) {
        if (neuralPatch instanceof ImageData) {
          this.rawNeuralCtx.putImageData(neuralPatch, 0, 0);
        } else {
          this.rawNeuralCtx.drawImage(neuralPatch, 0, 0, 96, 96);
        }
        const midSize = Math.min(panelW * 0.75, contentH * 0.75);
        const midX = p2X + (panelW - midSize) / 2;
        const midY = (contentH - midSize) / 2;

        this.ctx.imageSmoothingEnabled = false;
        this.ctx.drawImage(this.rawNeuralCanvas, midX, midY, midSize, midSize);
        this.drawPanelHeader('RAW NEURAL OUTPUT — WEBGPU', p2X + 16, 26, '#38bdf8');
      } else {
        this.drawPanelHeader('RAW NEURAL OUTPUT — WEBGPU', p2X + 16, 26, '#38bdf8');
        this.drawCenteredText('NEURAL MODEL NOT RUNNING', p2X + panelW / 2, contentH / 2, '#f87171', 'bold 13px monospace');
      }

      // PANEL 3: FINAL COMPOSITE
      const p3X = panelW * 2;
      if (sourceEl) {
        const aspect = 1376 / 768;
        const drawH = Math.floor(panelW / aspect);
        const offY = Math.floor((contentH - drawH) / 2);
        this.ctx.drawImage(sourceEl, p3X, offY, panelW, drawH);

        // Composite neural patch if active
        if (neuralPatch && this.patchBufferCtx) {
          const { x, y, width, height } = this.patchGeometry;
          const scaleX = panelW / 1376;
          const scaleY = drawH / 768;
          const destX = p3X + Math.round(x * scaleX);
          const destY = offY + Math.round(y * scaleY);
          const destW = Math.round(width * scaleX);
          const destH = Math.round(height * scaleY);

          this.patchBufferCtx.clearRect(0, 0, width, height);
          this.patchBufferCtx.imageSmoothingEnabled = true;
          this.patchBufferCtx.drawImage(this.rawNeuralCanvas, 0, 0, width, height);

          if (this.mask && this.mask.type === 'canvas') {
            this.patchBufferCtx.globalCompositeOperation = 'destination-in';
            this.patchBufferCtx.drawImage(this.mask.canvas, 0, 0, width, height);
            this.patchBufferCtx.globalCompositeOperation = 'source-over';
          }
          this.ctx.drawImage(this.patchBufferCanvas, destX, destY, destW, destH);
        }
      }
      this.drawPanelHeader('FINAL COMPOSITE', p3X + 16, 26, '#34d399');

      // Dividing grid lines
      this.ctx.strokeStyle = '#1e293b';
      this.ctx.lineWidth = 2;
      this.ctx.beginPath();
      this.ctx.moveTo(panelW, 0);
      this.ctx.lineTo(panelW, contentH);
      this.ctx.moveTo(panelW * 2, 0);
      this.ctx.lineTo(panelW * 2, contentH);
      this.ctx.stroke();

      // Bottom telemetry bar
      this.drawTelemetryBar(cW, cH);
      return;
    }

    // -------------------------------------------------------------
    // NORMAL MODE: 16:9 WIDESCREEN EXECUTIVE VIDEO CALL STAGE
    // High-definition real human portrait with neural lip sync
    // Strictly NO procedural cartoon eyelids or geometric deformations
    // -------------------------------------------------------------
    if (sourceEl) {
      // 1. Subtle 0.2Hz natural respiration drift (+/- 0.5px)
      const respirationY = Math.sin(nowSec * 1.25) * 0.5;

      this.ctx.drawImage(sourceEl, 0, respirationY, cW, cH);

      // 2. Composite neural mouth patch if actively speaking
      const isSpeaking = this.state === VOICE_STATES.SPEAKING;
      if (isSpeaking && neuralPatch && this.patchBufferCtx) {
        const { x, y, width, height } = this.patchGeometry;
        const scaleX = cW / 1376;
        const scaleY = cH / 768;

        const destX = Math.round(x * scaleX);
        const destY = Math.round((y + respirationY) * scaleY);
        const destW = Math.round(width * scaleX);
        const destH = Math.round(height * scaleY);

        if (neuralPatch instanceof ImageData) {
          this.rawNeuralCtx.putImageData(neuralPatch, 0, 0);
        } else {
          this.rawNeuralCtx.drawImage(neuralPatch, 0, 0, 96, 96);
        }

        // Scale 96x96 neural patch to 112x112 composite buffer
        this.patchBufferCtx.clearRect(0, 0, width, height);
        this.patchBufferCtx.imageSmoothingEnabled = true;
        this.patchBufferCtx.drawImage(this.rawNeuralCanvas, 0, 0, width, height);

        // Apply elliptical feather mask
        if (this.mask && this.mask.type === 'canvas') {
          this.patchBufferCtx.globalCompositeOperation = 'destination-in';
          this.patchBufferCtx.drawImage(this.mask.canvas, 0, 0, width, height);
          this.patchBufferCtx.globalCompositeOperation = 'source-over';
        }

        // Blend onto Sally's face
        this.ctx.drawImage(this.patchBufferCanvas, destX, destY, destW, destH);
      }
      // If NOT speaking or NO neural patch: mouth remains completely static!
      // Procedural fallback is strictly DISABLED.
    } else {
      // Background stage image loading or decoding
      this.ctx.fillStyle = '#030712';
      this.ctx.fillRect(0, 0, cW, cH);
    }
  }

  drawPanelHeader(text, x, y, color = '#ffffff') {
    this.ctx.save();
    this.ctx.font = 'bold 12px monospace';
    this.ctx.fillStyle = 'rgba(15, 23, 42, 0.85)';
    const tw = this.ctx.measureText(text).width;
    this.ctx.fillRect(x - 6, y - 13, tw + 12, 20);
    this.ctx.fillStyle = color;
    this.ctx.fillText(text, x, y);
    this.ctx.restore();
  }

  drawCenteredText(text, cx, cy, color = '#ffffff', font = '14px monospace') {
    this.ctx.save();
    this.ctx.font = font;
    this.ctx.textAlign = 'center';
    this.ctx.textBaseline = 'middle';
    this.ctx.fillStyle = color;
    this.ctx.fillText(text, cx, cy);
    this.ctx.restore();
  }

  drawTelemetryBar(cW, cH) {
    const barH = 44;
    const barY = cH - barH;

    this.ctx.save();
    this.ctx.fillStyle = 'rgba(3, 7, 18, 0.95)';
    this.ctx.fillRect(0, barY, cW, barH);
    this.ctx.strokeStyle = '#1e293b';
    this.ctx.lineWidth = 1;
    this.ctx.beginPath();
    this.ctx.moveTo(0, barY);
    this.ctx.lineTo(cW, barY);
    this.ctx.stroke();

    const telemetryText = `Model: Wav2Lip Generator ONNX (36.28M)  |  Execution: ${this.provider}  |  Inference: ${this.lastInferenceMs.toFixed(1)} ms  |  Neural FPS: ${this.neuralFps.toFixed(1)}  |  A/V Delta: ${this.avDeltaMs} ms  |  Frame: ${String(this.currentFrameIndex).padStart(5, '0')}  |  Fallback: DISABLED`;

    this.ctx.font = '12px monospace';
    this.ctx.fillStyle = '#cbd5e1';
    this.ctx.textAlign = 'center';
    this.ctx.textBaseline = 'middle';
    this.ctx.fillText(telemetryText, cW / 2, barY + barH / 2);
    this.ctx.restore();
  }

  destroy() {
    this.patchBufferCanvas = null;
    this.patchBufferCtx = null;
    this.rawNeuralCanvas = null;
    this.rawNeuralCtx = null;
    this.stageImage = null;
  }
}

