import test from 'node:test'
import assert from 'node:assert/strict'
import {planLegalTask} from '../src/lib/legal-task-planner.js'

test('plans an instruction-driven FTO workflow and extracts jurisdiction',()=>{const plan=planLegalTask('Run an FTO analysis for Product X in Germany.');assert.equal(plan.workflow_type,'fto');assert.equal(plan.jurisdiction,'Germany')})
test('plans an India FTO workflow without routing it to Europe',()=>{const plan=planLegalTask('Run an FTO analysis for Product X in India.');assert.equal(plan.workflow_type,'fto');assert.equal(plan.jurisdiction,'India')})
test('resolves jurisdictions outside the original hard-coded list',()=>{assert.equal(planLegalTask('Run an FTO analysis in Brazil.').jurisdiction,'Brazil');assert.equal(planLegalTask('Run an FTO analysis in Japan.').jurisdiction,'Japan');assert.equal(planLegalTask('Run an FTO analysis in South Africa.').jurisdiction,'South Africa')})
test('plans patentability without falsely completing a search',()=>{const plan=planLegalTask('Assess patentability of this invention.',{matterJurisdictions:['EPO']});assert.equal(plan.workflow_type,'patentability');assert.equal(plan.jurisdiction,'EPO')})
test('extracts an uppercase trademark and SaaS scope',()=>{const plan=planLegalTask('Check whether NOVARA is clear for SaaS in the EU.');assert.equal(plan.workflow_type,'trademark_clearance');assert.equal(plan.mark,'NOVARA');assert.equal(plan.jurisdiction,'EU');assert.match(plan.goods,/SaaS/)})
test('ordinary questions do not trigger a mutating workflow',()=>{assert.equal(planLegalTask('Explain what a trademark is.').workflow_type,null)})
test('routes explicit intake analysis before patentability keywords',()=>{const plan=planLegalTask("Give document type, invention summary, novelty signals, red flags, open questions and next steps. Don't draft claims; this is intake analysis.");assert.equal(plan.workflow_type,'invention_intake')})
test('routes a full US patent application draft request',()=>{const plan=planLegalTask('Act as a registered US Patent Attorney and draft a complete US patent application specification under 35 U.S.C. § 111 ready for USPTO provisional filing with Title, Field, Background, Summary, Detailed Description, claims and Abstract.');assert.equal(plan.workflow_type,'patent_drafting');assert.equal(plan.requires_matter,false)})
test('short draft prompts ask for clarification, detailed ones do not',()=>{assert.equal(planLegalTask('Draft a patent.').requires_clarification,true);assert.equal(planLegalTask('Draft a complete US provisional patent application for a decentralized key-recovery system using threshold Shamir secret sharing over ephemeral WebRTC data channels, with title, field, background, summary, detailed description, two independent claims and five dependent claims, plus abstract.').requires_clarification,false)})
