import test from 'node:test'
import assert from 'node:assert/strict'
import {buildEuipoTrademarkQuery,parseCourtListenerResults,parseEpoSearchXml,parseEuipoTrademarkResults,parseUsptoPatentResults,providerStatus,searchCourtListener,searchEpoOps,searchEuipoTrademarks,searchUsptoPatents} from '../src/lib/official-search-service.js'

const fixture=`<?xml version="1.0"?><ops:world-patent-data xmlns:ops="http://ops.epo.org"><ops:biblio-search><ops:search-result><exchange-documents><exchange-document><bibliographic-data><publication-reference><document-id><country>EP</country><doc-number>1234567</doc-number><kind>A1</kind></document-id></publication-reference><invention-title lang="en">Verified widget system</invention-title></bibliographic-data></exchange-document></exchange-documents></ops:search-result></ops:biblio-search></ops:world-patent-data>`

test('parses EPO OPS XML into canonical patent results',()=>{const results=parseEpoSearchXml(fixture);assert.equal(results.length,1);assert.equal(results[0].external_id,'EP1234567A1');assert.equal(results[0].title,'Verified widget system');assert.match(results[0].official_url,/espacenet/)})
test('provider status never claims an unconfigured provider is live',()=>{const providers=providerStatus({});assert.equal(providers.every(item=>item.configured===false),true)})
test('EPO connector labels missing credentials instead of faking search',async()=>{await assert.rejects(()=>searchEpoOps('widget',{}),error=>error.code==='PROVIDER_NOT_CONFIGURED')})
test('EPO connector authenticates and parses the official response',async()=>{const calls=[],fetchImpl=async(url,options)=>{calls.push({url,options});return url.includes('accesstoken')?{ok:true,json:async()=>({access_token:'token'})}:{ok:true,text:async()=>fixture}};const results=await searchEpoOps('ti=widget',{EPO_OPS_KEY:'key',EPO_OPS_SECRET:'secret'},{fetchImpl});assert.equal(results[0].external_id,'EP1234567A1');assert.equal(calls.length,2);assert.match(calls[1].options.headers.Authorization,/Bearer token/)})

const euipoFixture={trademarks:[{applicationNumber:'018123456',verbalElement:'SALLY',niceClasses:[9,42],applicants:[{name:'Example BV'}],status:'REGISTERED'}]}
test('builds a constrained EUIPO RSQL query',()=>{assert.equal(buildEuipoTrademarkQuery('SALLY <script>',[42,9,9,99]),'verbalElement==*SALLY script* and niceClasses=in=(42,9)')})
test('normalizes EUIPO trademark results',()=>{const[result]=parseEuipoTrademarkResults(euipoFixture);assert.equal(result.external_id,'018123456');assert.equal(result.mark,'SALLY');assert.deepEqual(result.nice_classes,[9,42]);assert.equal(result.owner,'Example BV');assert.equal(result.jurisdiction,'EU')})
test('EUIPO connector labels missing credentials instead of faking a search',async()=>{await assert.rejects(()=>searchEuipoTrademarks({mark:'SALLY'},{}),error=>error.code==='PROVIDER_NOT_CONFIGURED')})
test('EUIPO connector rejects sandbox endpoints as professional evidence',async()=>{await assert.rejects(()=>searchEuipoTrademarks({mark:'SALLY'},{EUIPO_CLIENT_ID:'id',EUIPO_CLIENT_SECRET:'secret',EUIPO_API_BASE:'https://sandbox.example.test'}),error=>error.code==='SANDBOX_NOT_ALLOWED')})
test('EUIPO connector authenticates, uses zero-based pages, and parses results',async()=>{const calls=[],fetchImpl=async(url,options)=>{calls.push({url:String(url),options});return calls.length===1?{ok:true,json:async()=>({access_token:'eu-token'})}:{ok:true,json:async()=>euipoFixture}};const results=await searchEuipoTrademarks({mark:'SALLY',classes:[9,42],page:0,size:25},{EUIPO_CLIENT_ID:'client',EUIPO_CLIENT_SECRET:'secret'},{fetchImpl});assert.equal(results[0].external_id,'018123456');assert.equal(calls.length,2);const searchUrl=new URL(calls[1].url);assert.equal(searchUrl.searchParams.get('page'),'0');assert.match(searchUrl.searchParams.get('query'),/verbalElement/);assert.equal(calls[1].options.headers['X-IBM-Client-Id'],'client');assert.equal(calls[1].options.headers.Authorization,'Bearer eu-token')})

const usptoFixture={results:[{patentNumber:'US11234567B2',patentTitle:'Widget calibration system',patentDate:'2022-04-05'}]}
test('normalizes USPTO patent results',()=>{const[result]=parseUsptoPatentResults(usptoFixture);assert.equal(result.external_id,'US11234567B2');assert.equal(result.title,'Widget calibration system');assert.equal(result.country,'US');assert.match(result.official_url,/uspto\.gov/)})
test('USPTO connector labels missing credentials instead of faking search',async()=>{await assert.rejects(()=>searchUsptoPatents('widget',{}),error=>error.code==='PROVIDER_NOT_CONFIGURED')})
test('USPTO connector sends the API key header and parses results',async()=>{const calls=[],fetchImpl=async(url,options)=>{calls.push({url:String(url),options});return{ok:true,json:async()=>usptoFixture}};const results=await searchUsptoPatents('widget',{USPTO_API_KEY:'key'},{fetchImpl});assert.equal(results[0].external_id,'US11234567B2');assert.equal(calls[0].options.headers['X-API-KEY'],'key')})
test('USPTO connector maps auth failures honestly',async()=>{const fetchImpl=async()=>({ok:false,status:403});await assert.rejects(()=>searchUsptoPatents('widget',{USPTO_API_KEY:'bad'},{fetchImpl}),error=>error.code==='PROVIDER_AUTH_FAILED')})

const clFixture={count:1,results:[{absolute_url:'/opinion/123/example-v-sample/',caseName:'Example v. Sample',court:'ca9',dateFiled:'2021-06-01',citeCount:14}]}
test('normalizes CourtListener opinions',()=>{const[result]=parseCourtListenerResults(clFixture);assert.equal(result.title,'Example v. Sample');assert.equal(result.court,'ca9');assert.match(result.official_url,/courtlistener\.com\/opinion/)})
test('CourtListener connector labels missing credentials instead of faking search',async()=>{await assert.rejects(()=>searchCourtListener('jurisdiction',{}),error=>error.code==='PROVIDER_NOT_CONFIGURED')})
test('CourtListener connector sends the token and parses results',async()=>{const calls=[],fetchImpl=async(url,options)=>{calls.push({url:String(url),options});return{ok:true,json:async()=>clFixture}};const results=await searchCourtListener('personal jurisdiction',{COURTLISTENER_TOKEN:'tok'},{fetchImpl});assert.equal(results[0].title,'Example v. Sample');assert.equal(calls[0].options.headers.Authorization,'Token tok');assert.match(calls[0].url,/type=o/)})
test('provider status covers all four official providers',()=>{const ids=providerStatus({}).map(p=>p.id);assert.ok(ids.includes('uspto_patent'));assert.ok(ids.includes('courtlistener'))})
