import {useState} from 'react'
import {motion} from 'framer-motion'
import {ArrowLeft,ArrowRight,Eye,EyeOff,LockKeyhole,Mail,Sparkles} from 'lucide-react'

function Mark(){return <span className="authMark"><img src="/sallyip-logo.png" alt="SallyIP"/></span>}

export default function AuthPage({onHome,onSuccess}){
  const [mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const submit=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,name,email,password})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Unable to continue');onSuccess(data.user)}catch(error){setError(error.message)}finally{setBusy(false)}}
  return <div className="authPage"><button className="authHome" onClick={onHome}><ArrowLeft/> Home</button><motion.main initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><Mark/><span className="authEyebrow"><Sparkles/> SALLYIP 4.1 PRO</span><h1>{mode==='login'?'Welcome back.':'Create your research workspace.'}</h1><p>{mode==='login'?'Continue your private IP research with Sally.':'Secure conversations, private sources, and one Sally intelligence layer.'}</p><div className="authTabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Log in</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('')}}>Sign up</button></div><form onSubmit={submit}>{mode==='signup'&&<label><span>Full name</span><div><Sparkles/><input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Carlos Northon" required/></div></label>}<label><span>Email</span><div><Mail/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></div></label><label><span>Password</span><div><LockKeyhole/><input type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" minLength={8} required/><button type="button" onClick={()=>setShow(value=>!value)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="authError">{error}</div>}<button className="authSubmit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in to Sally':'Create account'}{!busy&&<ArrowRight/>}</button></form><small>By continuing, you agree to use Sally as research assistance and verify important legal conclusions.</small></motion.main></div>
}
