import {useEffect,useMemo,useState} from 'react'
import {motion} from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {ArrowRight,ChevronDown,Copy,MessageSquare,Paperclip,Plus,Send,X} from 'lucide-react'

const STORAGE_KEY='sallyip-chat-history-v1'
const suggestions=['Summarize a patent claim','Compare two trademarks','Build an IP research plan','Explain prior-art searching']
const makeChat=()=>({id:crypto.randomUUID(),title:'New conversation',messages:[],createdAt:Date.now()})
const titleFor=text=>text.trim().replace(/\s+/g,' ').slice(0,42)+(text.trim().length>42?'…':'')
function Mark({className=''}){return <span className={`brandMark ${className}`}><img src="/sallyip-logo.png" alt=""/></span>}

export default function ChatPage({onHome}){
  const [chats,setChats]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return saved.length?saved:[makeChat()]}catch{return[makeChat()]}})
  const [activeId,setActiveId]=useState(()=>chats[0].id)
  const [input,setInput]=useState('')
  const [loading,setLoading]=useState(false)
  const active=useMemo(()=>chats.find(chat=>chat.id===activeId)||chats[0],[chats,activeId])
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(chats)),[chats])
  const updateActive=updater=>setChats(all=>all.map(chat=>chat.id===activeId?updater(chat):chat))
  const newChat=()=>{if(active?.messages.length===0){setInput('');return}const chat=makeChat();setChats(all=>[chat,...all]);setActiveId(chat.id);setInput('')}
  const openChat=id=>{if(loading)return;setActiveId(id);setInput('')}
  const send=async(text=input)=>{const clean=text.trim();if(!clean||loading)return;const next=[...(active?.messages||[]),{role:'user',content:clean}];updateActive(chat=>({...chat,title:chat.messages.length?chat.title:titleFor(clean),messages:next}));setInput('');setLoading(true);try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'SallyIP could not respond');const answer={role:'assistant',content:data.choices?.[0]?.message?.content||'No response was returned.'};updateActive(chat=>({...chat,messages:[...chat.messages,answer]}))}catch(error){updateActive(chat=>({...chat,messages:[...chat.messages,{role:'assistant',content:`I couldn't connect right now. ${error.message}`}]}))}finally{setLoading(false)}}
  const messages=active?.messages||[]
  return <div className="sallyChat"><aside className="chatRail"><button className="chatBrand" onClick={onHome}><Mark/><span><b>SallyIP</b><small>Labs</small></span></button><button className="newChat" onClick={newChat}><Plus/> New chat</button><div className="chatHistory"><small>RECENT</small>{chats.filter(chat=>chat.messages.length).map(chat=><button className={chat.id===activeId?'active':''} onClick={()=>openChat(chat.id)} key={chat.id}><MessageSquare/><span>{chat.title}</span></button>)}</div><div className="chatUser"><span>CN</span><div><b>Carlos Northon</b><small>Research workspace</small></div></div></aside><main className="chatMain"><header className="chatTop"><button className="mobileChatLogo" onClick={onHome}><Mark/></button><button className="modelPicker"><span>SallyIP 4.1 Pro</span><small>Research model</small><ChevronDown/></button><div><span className="modelLive"><i/> ONLINE</span><button className="iconBtn" onClick={onHome}><X/></button></div></header><section className={`chatThread ${messages.length?'hasMessages':''}`}>{messages.length===0?<motion.div className="chatWelcome" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><Mark className="chatHeroMark"/><span>SALLYIP 4.1 PRO</span><h1>What are we<br/><em>researching today?</em></h1><p>Explore patents, trademarks, copyright, prior art, and intellectual-property strategy with a specialist AI research partner.</p><div className="promptGrid">{suggestions.map((text,index)=><button key={text} onClick={()=>send(text)}><span>0{index+1}</span>{text}<ArrowRight/></button>)}</div></motion.div>:<div className="messageList">{messages.map((message,index)=><motion.article className={`chatMessage ${message.role}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} key={index}>{message.role==='assistant'?<Mark/>:<span className="messageAvatar">CN</span>}<div><small>{message.role==='assistant'?'SALLYIP 4.1 PRO':'YOU'}</small><div className="markdownAnswer"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content}</ReactMarkdown></div>{message.role==='assistant'&&<button className="copyAnswer" onClick={()=>navigator.clipboard.writeText(message.content)}><Copy/> Copy</button>}</div></motion.article>)}{loading&&<article className="chatMessage assistant"><Mark/><div><small>SALLYIP 4.1 PRO</small><div className="thinking"><i/><i/><i/></div></div></article>}</div>}</section><div className="composerWrap"><div className="composer"><button aria-label="Attach file"><Paperclip/></button><textarea value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}}} placeholder="Ask SallyIP 4.1 Pro" rows="1"/><button className="sendChat" disabled={!input.trim()||loading} onClick={()=>send()}><Send/></button></div><small>SallyIP can make mistakes. Verify important legal information with authoritative sources.</small></div></main></div>
}
