import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,Database,GitFork,Network,RefreshCw,ShieldCheck,X} from 'lucide-react'

const typeLabel=value=>String(value||'').replaceAll('_',' ')
const typeOrder=['patent','patent_claim','trademark','product','party','person','licence','document','evidence','event','case','legislation','argument','deadline','domain']

export default function IpKnowledgeGraphWorkspace({matterId}){
  const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[graph,setGraph]=useState({entities:[],relationships:[]}),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(null)
  const load=async()=>{if(!matterId)return;setBusy(true);setError('');try{const response=await fetch(`/api/ip-graph?matter_id=${encodeURIComponent(matterId)}`),data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'IP graph could not be loaded');setGraph(data)}catch(err){setError(err.message)}finally{setBusy(false)}}
  useEffect(()=>{if(open)load()},[open,matterId])
  const byId=useMemo(()=>new Map(graph.entities.map(item=>[item.id,item])),[graph.entities])
  const types=useMemo(()=>typeOrder.filter(type=>graph.entities.some(item=>item.entity_type===type)),[graph.entities])
  const visible=filter==='all'?graph.entities:graph.entities.filter(item=>item.entity_type===filter)
  const links=selected?graph.relationships.filter(item=>item.from_entity_id===selected.id||item.to_entity_id===selected.id):graph.relationships
  const close=()=>{setOpen(false);setSelected(null);setError('')}
  return <><div className="graphLaunch"><button onClick={()=>setOpen(true)}><Network/>IP knowledge graph</button></div>{open&&<div className="ipToolOverlay" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="ipToolModal graphModal"><header><div><span>SALLY MATTER BRAIN / CONNECTED IP DATA</span><h2>IP knowledge graph</h2></div><div className="graphHeaderActions"><button onClick={load} title="Refresh"><RefreshCw/></button><button onClick={close}><X/></button></div></header>{!matterId?<div className="ipToolError">Select or create a matter first.</div>:<><div className="graphStats"><article><Database/><div><strong>{graph.entities.length}</strong><small>entities</small></div></article><article><GitFork/><div><strong>{graph.relationships.length}</strong><small>relationships</small></div></article><article><ShieldCheck/><div><strong>{graph.entities.filter(item=>item.source_status==='verified').length}</strong><small>verified entities</small></div></article></div><div className="graphFilters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button>{types.map(type=><button className={filter===type?'active':''} onClick={()=>setFilter(type)} key={type}>{typeLabel(type)} <b>{graph.entities.filter(item=>item.entity_type===type).length}</b></button>)}</div><div className="graphWorkspace"><div className="graphNodes">{visible.map(item=><button className={`${item.source_status} ${selected?.id===item.id?'selected':''}`} onClick={()=>setSelected(current=>current?.id===item.id?null:item)} key={item.id}><span>{typeLabel(item.entity_type)}</span><strong>{item.name}</strong><small>{item.canonical_identifier||item.jurisdiction||'No canonical identifier'}</small><em>{typeLabel(item.source_status)}</em></button>)}{!visible.length&&!busy&&<div className="claimChartEmpty">No graph entities match this filter.</div>}</div><aside className="graphRelationships"><div><span>{selected?'CONNECTED TO':'RELATIONSHIPS'}</span><strong>{selected?.name||'Matter graph'}</strong></div>{links.map(item=>{const from=byId.get(item.from_entity_id),to=byId.get(item.to_entity_id);return <article key={item.id}><div><small>{typeLabel(from?.entity_type)}</small><b>{from?.name||'Unknown entity'}</b></div><span>{typeLabel(item.relationship_type)}<ArrowRight/></span><div><small>{typeLabel(to?.entity_type)}</small><b>{to?.name||'Unknown entity'}</b></div>{item.confidence!=null&&<em>{Math.round(Number(item.confidence)*100)}% recorded confidence</em>}</article>})}{!links.length&&<div className="claimChartEmpty">No relationships recorded.</div>}</aside></div></>}{busy&&<div className="graphLoading">Loading connected matter data…</div>}{error&&<div className="ipToolError">{error}</div>}</section></div>}</>
}

