import {useEffect,useState} from 'react'
import {CalendarRange,Check,Link2,Plus,Scale,Search,X} from 'lucide-react'

const label=value=>String(value||'').replaceAll('_',' ')
const emptyIssue={title:'',description:'',issue_type:'evidence'}
const emptyEvent={issue_id:'',event_date:'',title:'',description:'',significance:'',passage_id:''}
const emptyItem={issue_id:'',required_fact:'',legal_relevance:'',burden:'',witness_entity_id:'',gap_note:''}

export default function LitigationEvidenceWorkspace({matterId,onResult}){
  const[open,setOpen]=useState(false),[tab,setTab]=useState('chronology'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[issue,setIssue]=useState(emptyIssue),[event,setEvent]=useState(emptyEvent),[item,setItem]=useState(emptyItem),[link,setLink]=useState({object_type:'chronology_event',object_id:'',passage_id:'',evidence_type:'supports',weight:'unassessed'})
  const request=async(options={})=>{const response=await fetch(options.url||'/api/litigation-evidence',options.fetch),payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message||'Evidence operation failed');return payload}
  const load=async()=>{if(!matterId)return;setBusy(true);setError('');try{setData(await request({url:`/api/litigation-evidence?matter_id=${encodeURIComponent(matterId)}`}))}catch(err){setError(err.message)}finally{setBusy(false)}}
  useEffect(()=>{if(open)load()},[open,matterId])
  const act=async body=>{setBusy(true);setError('');try{const next=await request({fetch:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}});setData(next);return next}catch(err){setError(err.message);throw err}finally{setBusy(false)}}
  const addIssue=async e=>{e.preventDefault();try{await act({action:'create_issue',matter_id:matterId,...issue});setIssue(emptyIssue)}catch{}}
  const addEvent=async e=>{e.preventDefault();try{const next=await act({action:'create_event',matter_id:matterId,...event,passage_id:event.passage_id||null});setEvent(emptyEvent);onResult(`## Matter chronology updated\n\nAdded **${event.title}** on ${event.event_date}. It remains proposed until a verified pinpoint source supports it.`,{task_class:'LITIGATION_CHRONOLOGY',specialists:['Sally Litigation','Sally Evidence','Sally Verification'],source_basis:event.passage_id?'uploaded_document':'user_supplied'})}catch{}}
  const addItem=async e=>{e.preventDefault();try{await act({action:'create_item',...item});setItem(emptyItem);onResult(`## Evidence matrix updated\n\nAdded required fact: **${item.required_fact}**. Sally records it as an open gap until supporting evidence is attached and verified.`,{task_class:'LITIGATION_EVIDENCE_MATRIX',specialists:['Sally Litigation','Sally Evidence','Sally Verification'],source_basis:'user_supplied'})}catch{}}
  const attach=async e=>{e.preventDefault();try{await act({action:'attach_evidence',...link});setLink({...link,passage_id:''})}catch{}}
  const reviewEvent=async(eventId,status)=>{try{await act({action:'review_event',event_id:eventId,review_status:status})}catch{}}
  const reviewItem=async(itemId,status,gapNote)=>{try{await act({action:'review_item',item_id:itemId,assessment_status:status,gap_note:gapNote})}catch{}}
  const propose=async()=>{try{const next=await act({action:'propose_chronology',matter_id:matterId});onResult(`## Chronology extraction completed\n\nSally identified ${next.events.filter(row=>row.review_status==='proposed').length} proposed dated events from matter-scoped source passages. Every event still requires lawyer verification.`,{task_class:'LITIGATION_CHRONOLOGY_EXTRACTION',specialists:['Sally Litigation','Sally Evidence','Sally Verification'],source_basis:'uploaded_document'})}catch{}}
  return <><div className="litigationEvidenceLaunch"><button onClick={()=>setOpen(true)}><Scale/>Chronology & evidence</button></div>{open&&<div className="ipToolOverlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="ipToolModal litigationEvidenceModal"><header><div><span>SALLY LITIGATION / EVIDENCE / VERIFICATION</span><h2>Matter chronology and evidence matrix</h2></div><button onClick={()=>setOpen(false)}><X/></button></header>{!matterId?<div className="ipToolError">Select or create a matter first.</div>:<><nav className="evidenceTabs"><button className={tab==='chronology'?'active':''} onClick={()=>setTab('chronology')}><CalendarRange/>Chronology</button><button className={tab==='matrix'?'active':''} onClick={()=>setTab('matrix')}><Scale/>Evidence matrix</button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Link2/>Evidence links</button></nav>{data&&<div className="evidenceStats"><span><b>{data.events.length}</b> events</span><span><b>{data.summary.verified_events}</b> verified</span><span><b>{data.summary.open_gaps}</b> open gaps</span><span><b>{data.summary.contrary_evidence}</b> contrary passages</span></div>}{tab==='chronology'&&<Chronology data={data} issue={issue} setIssue={setIssue} event={event} setEvent={setEvent} addIssue={addIssue} addEvent={addEvent} propose={propose} review={reviewEvent} busy={busy}/>} {tab==='matrix'&&<Matrix data={data} item={item} setItem={setItem} addItem={addItem} review={reviewItem} busy={busy}/>} {tab==='sources'&&<EvidenceLinks data={data} link={link} setLink={setLink} attach={attach} busy={busy}/>}</>}{error&&<div className="ipToolError">{error}</div>}</section></div>}</>
}

function IssueForm({issue,setIssue,addIssue,busy}){return <form className="evidenceInlineForm" onSubmit={addIssue}><input required value={issue.title} onChange={e=>setIssue({...issue,title:e.target.value})} placeholder="Issue, e.g. knowledge of the patent"/><select value={issue.issue_type} onChange={e=>setIssue({...issue,issue_type:e.target.value})}><option value="infringement">Infringement</option><option value="validity">Validity</option><option value="ownership">Ownership</option><option value="remedy">Remedy</option><option value="procedure">Procedure</option><option value="evidence">Evidence</option><option value="other">Other</option></select><button disabled={busy}><Plus/>Add issue</button></form>}
function Chronology({data,issue,setIssue,event,setEvent,addIssue,addEvent,propose,review,busy}){return <div className="litigationPane"><IssueForm {...{issue,setIssue,addIssue,busy}}/><form className="chronologyForm" onSubmit={addEvent}><select value={event.issue_id} onChange={e=>setEvent({...event,issue_id:e.target.value})}><option value="">No linked issue</option>{data?.issues.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select><input required type="date" value={event.event_date} onChange={e=>setEvent({...event,event_date:e.target.value})}/><input required value={event.title} onChange={e=>setEvent({...event,title:e.target.value})} placeholder="What happened?"/><textarea value={event.description} onChange={e=>setEvent({...event,description:e.target.value})} placeholder="Event description"/><textarea value={event.significance} onChange={e=>setEvent({...event,significance:e.target.value})} placeholder="Why this matters"/><select value={event.passage_id} onChange={e=>setEvent({...event,passage_id:e.target.value})}><option value="">No source passage yet</option>{data?.passages.map(p=><option key={p.passage_id} value={p.passage_id}>{p.source_title} · {p.locator}</option>)}</select><button disabled={busy}><Plus/>Add proposed event</button></form><button className="extractChronology" disabled={busy||!data?.passages.length} onClick={propose}><Search/>Extract dated events from matter sources</button><div className="chronologyTimeline">{data?.events.map(row=><article key={row.id} className={row.review_status}><time>{String(row.event_date).slice(0,10)}</time><div><span>{row.issue_title||'Matter event'} · {label(row.provenance_basis)}</span><h3>{row.title}</h3><p>{row.description}</p>{row.significance&&<small>{row.significance}</small>}<div className="evidenceChips">{row.evidence.map(e=><b key={e.passage_id} className={e.relation_type}>{e.relation_type} · {e.source_title} {e.locator} {e.source_verified?'✓ verified':'· unverified'}</b>)}</div></div><select value={row.review_status} onChange={e=>review(row.id,e.target.value)}><option value="proposed">Proposed</option><option value="verified">Verified</option><option value="disputed">Disputed</option><option value="rejected">Rejected</option></select></article>)}</div></div>}
function Matrix({data,item,setItem,addItem,review,busy}){return <div className="litigationPane"><form className="matrixForm" onSubmit={addItem}><select required value={item.issue_id} onChange={e=>setItem({...item,issue_id:e.target.value})}><option value="">Select issue</option>{data?.issues.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select><input required value={item.required_fact} onChange={e=>setItem({...item,required_fact:e.target.value})} placeholder="Fact that must be proved"/><input value={item.legal_relevance} onChange={e=>setItem({...item,legal_relevance:e.target.value})} placeholder="Legal relevance"/><input value={item.burden} onChange={e=>setItem({...item,burden:e.target.value})} placeholder="Burden / standard"/><select value={item.witness_entity_id} onChange={e=>setItem({...item,witness_entity_id:e.target.value})}><option value="">No witness linked</option>{data?.witnesses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><input value={item.gap_note} onChange={e=>setItem({...item,gap_note:e.target.value})} placeholder="Current evidence gap"/><button disabled={busy||!data?.issues.length}><Plus/>Add required fact</button></form><div className="matrixTable"><div className="matrixHead"><b>Issue / required fact</b><b>Supporting evidence</b><b>Contrary evidence</b><b>Witness / gap</b><b>Assessment</b></div>{data?.items.map(row=><article key={row.id}><div><span>{row.issue_title}</span><strong>{row.required_fact}</strong><small>{row.legal_relevance}</small></div><EvidenceList items={row.evidence.filter(e=>e.evidence_type==='supports')}/><EvidenceList items={row.evidence.filter(e=>e.evidence_type==='contradicts')}/><div><span>{row.witness_name||'No witness linked'}</span><small>{row.gap_note||'No gap note'}</small></div><select value={row.assessment_status} onChange={e=>review(row.id,e.target.value,row.gap_note)}><option value="gap">Gap</option><option value="partially_supported">Partially supported</option><option value="supported">Supported</option><option value="disputed">Disputed</option><option value="not_required">Not required</option></select></article>)}</div></div>}
function EvidenceList({items}){return <div className="matrixEvidence">{items.length?items.map(e=><span key={e.passage_id}>{e.source_title} · {e.locator}<small>{e.weight} · {e.source_verified?'verified':'unverified'}</small></span>):<em>None</em>}</div>}
function EvidenceLinks({data,link,setLink,attach,busy}){const objects=link.object_type==='chronology_event'?data?.events:data?.items;return <div className="litigationPane"><p className="officialSearchNote">Attach exact matter-scoped passages. Supporting evidence must pass source verification before an event or fact can be marked verified/supported.</p><form className="evidenceLinkForm" onSubmit={attach}><select value={link.object_type} onChange={e=>setLink({...link,object_type:e.target.value,object_id:''})}><option value="chronology_event">Chronology event</option><option value="evidence_item">Evidence matrix item</option></select><select required value={link.object_id} onChange={e=>setLink({...link,object_id:e.target.value})}><option value="">Select target</option>{objects?.map(o=><option value={o.id} key={o.id}>{o.title||o.required_fact}</option>)}</select><select required value={link.passage_id} onChange={e=>setLink({...link,passage_id:e.target.value})}><option value="">Select pinpoint passage</option>{data?.passages.map(p=><option value={p.passage_id} key={p.passage_id}>{p.source_title} · {p.locator} · {p.verified_at?'verified':'unverified'}</option>)}</select><select value={link.evidence_type} onChange={e=>setLink({...link,evidence_type:e.target.value})}><option value="supports">Supports</option><option value="contradicts">Contradicts</option><option value="context">Context</option></select>{link.object_type==='evidence_item'&&<select value={link.weight} onChange={e=>setLink({...link,weight:e.target.value})}><option value="unassessed">Unassessed</option><option value="strong">Strong</option><option value="moderate">Moderate</option><option value="weak">Weak</option></select>}<button disabled={busy}><Link2/>Attach evidence</button></form></div>}
