import {useEffect,useState} from 'react'
import {GitFork,Link2,Plus,ShieldCheck,X} from 'lucide-react'

const emptyMember={title:'',application_number:'',publication_number:'',jurisdiction:'',kind_code:'',priority_date:'',filing_date:'',legal_status:'unknown',source_basis:'user_supplied',source_reference:''}

export default function PatentFamilyWorkspace({matterId,onResult}){
  const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[families,setFamilies]=useState([]),[family,setFamily]=useState(null),[mode,setMode]=useState(null)
  const[createForm,setCreateForm]=useState({name:'',family_type:'declared',earliest_priority_date:''}),[member,setMember]=useState(emptyMember),[link,setLink]=useState({from_member_id:'',to_member_id:'',relationship_type:'claims_priority_to',source_basis:'user_supplied',note:''})
  useEffect(()=>{if(open&&matterId)loadFamilies()},[open,matterId])
  const request=async(url,options)=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Patent family operation failed');return data}
  const loadFamilies=async()=>{setBusy(true);setError('');try{setFamilies((await request(`/api/patent-families?matter_id=${encodeURIComponent(matterId)}`)).families)}catch(err){setError(err.message)}finally{setBusy(false)}}
  const load=async id=>{setBusy(true);setError('');try{setFamily(await request(`/api/patent-families?family_id=${encodeURIComponent(id)}`))}catch(err){setError(err.message)}finally{setBusy(false)}}
  const act=async body=>{setBusy(true);setError('');try{const data=await request('/api/patent-families',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setFamily(data);return data}catch(err){setError(err.message)}finally{setBusy(false)}}
  const create=async event=>{event.preventDefault();if(!matterId)return setError('Select a matter first.');const data=await act({action:'create',matter_id:matterId,...createForm});if(data)onResult(`## Patent family created\n\n**${data.family.name}** is now a first-class matter graph entity. Add applications and explicit sourced family relationships to build the chronology.`,{task_class:'PATENT_FAMILY',specialists:['Sally Patents','Sally Evidence','Sally Verification'],source_basis:'user_supplied'})}
  const addMember=async event=>{event.preventDefault();const data=await act({action:'add_member',family_id:family.family.id,...member});if(data){setMember(emptyMember);setMode(null)}}
  const addLink=async event=>{event.preventDefault();const data=await act({action:'link_members',family_id:family.family.id,...link});if(data){setLink({from_member_id:'',to_member_id:'',relationship_type:'claims_priority_to',source_basis:'user_supplied',note:''});setMode(null)}}
  const close=()=>{setOpen(false);setFamily(null);setMode(null);setError('')}

  return <><div className="familyLaunch"><button onClick={()=>setOpen(true)}><GitFork/>Patent family</button></div>{open&&<div className="ipToolOverlay" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="ipToolModal familyModal"><header><div><span>SALLY PATENTS / FAMILY GRAPH</span><h2>{family?family.family.name:'Build a patent family'}</h2></div><button type="button" onClick={close}><X/></button></header>{!matterId?<div className="ipToolError">Select or create a matter first.</div>:family?<FamilyView family={family} busy={busy} mode={mode} setMode={setMode} member={member} setMember={setMember} link={link} setLink={setLink} addMember={addMember} addLink={addLink}/>:<CreateView form={createForm} setForm={setCreateForm} create={create} families={families} load={load} busy={busy}/>} {error&&<div className="ipToolError">{error}</div>}</section></div>}</>
}

function CreateView({form,setForm,create,families,load,busy}){return <form onSubmit={create}><div className="ipToolGrid"><label>Family name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Family type<select value={form.family_type} onChange={e=>setForm({...form,family_type:e.target.value})}><option value="declared">Declared / being assembled</option><option value="simple">Simple family</option><option value="extended">Extended family</option></select></label></div><label>Earliest claimed priority<input type="date" value={form.earliest_priority_date} onChange={e=>setForm({...form,earliest_priority_date:e.target.value})}/></label>{families.length>0&&<label>Or reopen a family<select defaultValue="" onChange={e=>e.target.value&&load(e.target.value)}><option value="">Select family</option>{families.map(item=><option key={item.id} value={item.id}>{item.name} · {item.member_count} members</option>)}</select></label>}<p className="officialSearchNote">A declared family records the lawyer’s working graph. It is not treated as an official INPADOC family unless retrieved and verified from an official source.</p><footer><span><ShieldCheck/>Matter-scoped provenance</span><button disabled={busy}>{busy?'Creating…':'Create family'}</button></footer></form>}

function FamilyView({family,busy,mode,setMode,member,setMember,link,setLink,addMember,addLink}){return <><div className="familyMeta"><span>{family.family.family_type} family</span><span>{family.members.length} members</span><span>{family.links.length} relationships</span><span>Priority {family.family.earliest_priority_date||'unconfirmed'}</span></div><div className="familyGraph">{family.layers.length?family.layers.map((layer,index)=><div className="familyLayer" key={index}>{layer.map(item=><article key={item.id}><small>{item.jurisdiction||'—'} {item.kind_code||''}</small><strong>{item.publication_number||item.application_number}</strong><span>{item.priority_date||item.filing_date||'Date unknown'}</span><em>{item.source_basis.replaceAll('_',' ')}</em></article>)}</div>):<div className="claimChartEmpty">Add the priority filing, PCT, regional applications, and national validations.</div>}{family.layers.map((_,index)=>index<family.layers.length-1&&<i className="familyConnector" key={`line-${index}`} style={{top:`${((index+1)/family.layers.length)*100}%`}}/>)}</div><div className="familyActions"><button onClick={()=>setMode(mode==='member'?null:'member')}><Plus/>Add family member</button><button disabled={family.members.length<2} onClick={()=>setMode(mode==='link'?null:'link')}><Link2/>Link members</button></div>{mode==='member'&&<MemberForm member={member} setMember={setMember} submit={addMember} busy={busy}/>} {mode==='link'&&<LinkForm members={family.members} link={link} setLink={setLink} submit={addLink} busy={busy}/>}<div className="familyLinks">{family.links.map(item=><article key={item.id}><span>{item.from_publication||'Application'}</span><b>{item.relationship_type.replaceAll('_',' ')}</b><span>{item.to_publication||'Application'}</span><small>{item.source_basis.replaceAll('_',' ')}{item.verified_at?' · verified':''}</small></article>)}</div></>}

function MemberForm({member,setMember,submit,busy}){return <form className="familySubform" onSubmit={submit}><div className="ipToolGrid"><label>Publication number<input value={member.publication_number} onChange={e=>setMember({...member,publication_number:e.target.value})}/></label><label>Application number<input value={member.application_number} onChange={e=>setMember({...member,application_number:e.target.value})}/></label><label>Jurisdiction<input value={member.jurisdiction} onChange={e=>setMember({...member,jurisdiction:e.target.value})} placeholder="WO / EP / US / GB"/></label><label>Kind code<input value={member.kind_code} onChange={e=>setMember({...member,kind_code:e.target.value})} placeholder="A1 / B1"/></label><label>Priority date<input type="date" value={member.priority_date} onChange={e=>setMember({...member,priority_date:e.target.value})}/></label><label>Filing date<input type="date" value={member.filing_date} onChange={e=>setMember({...member,filing_date:e.target.value})}/></label></div><label>Source basis<select value={member.source_basis} onChange={e=>setMember({...member,source_basis:e.target.value})}><option value="user_supplied">User supplied</option><option value="uploaded_document">Uploaded document</option><option value="retrieved_source">Retrieved source</option></select></label><label>Source reference<input value={member.source_reference} onChange={e=>setMember({...member,source_reference:e.target.value})}/></label><button disabled={busy}>Add member</button></form>}

function LinkForm({members,link,setLink,submit,busy}){return <form className="familySubform" onSubmit={submit}><div className="ipToolGrid"><label>From<select required value={link.from_member_id} onChange={e=>setLink({...link,from_member_id:e.target.value})}><option value="">Select member</option>{members.map(item=><option key={item.id} value={item.id}>{item.publication_number||item.application_number}</option>)}</select></label><label>To<select required value={link.to_member_id} onChange={e=>setLink({...link,to_member_id:e.target.value})}><option value="">Select member</option>{members.map(item=><option key={item.id} value={item.id}>{item.publication_number||item.application_number}</option>)}</select></label></div><label>Relationship<select value={link.relationship_type} onChange={e=>setLink({...link,relationship_type:e.target.value})}><option value="claims_priority_to">Claims priority to</option><option value="continuation_of">Continuation of</option><option value="divisional_of">Divisional of</option><option value="national_phase_of">National phase of</option><option value="validation_of">Validation of</option><option value="family_equivalent">Family equivalent</option></select></label><label>Evidence note<textarea value={link.note} onChange={e=>setLink({...link,note:e.target.value})}/></label><button disabled={busy}>Save relationship</button></form>}
