import {motion} from 'framer-motion'
import {ArrowLeft,ArrowRight,Check,GraduationCap,Sparkles} from 'lucide-react'

const plans=[
  {name:'Basic',price:'$9',note:'For independent researchers',features:['SallyIP 4.1 Pro chat','100 research messages / month','3 saved research sessions','Core patent and trademark tools'],cta:'Start Basic'},
  {name:'Pro',price:'$49',note:'For serious IP professionals',featured:true,features:['Everything in Basic','Unlimited research conversations','25 document analyses / month','Priority SallyIP responses','Exportable research reports'],cta:'Choose Pro'},
  {name:'Scale',price:'$199',note:'For growing legal and IP teams',features:['Everything in Pro','5 workspace members','Private knowledge collections','Shared research library','Advanced provenance records','Priority support'],cta:'Choose Scale'},
  {name:'Universities',price:'Free',note:'For qualifying academic institutions',university:true,features:['Research and teaching access','Student contribution workspace','Shared academic benchmarks','Responsible AI research tools','Institutional onboarding'],cta:'Contact team'}
]

function Mark(){return <span className="brandMark"><img src="/sallyip-logo.png" alt=""/></span>}
export default function PricingPage({onHome,onChat}){return <div className="pricingPage"><header className="pricingNav"><button className="pricingBrand" onClick={onHome}><Mark/><b>SallyIP</b><span>Labs</span></button><nav><button onClick={onHome}>Platform</button><button className="active">Pricing</button><button onClick={onChat}>SallyIP Chat</button></nav><button className="pricingBack" onClick={onHome}><ArrowLeft/> Back home</button></header><main><motion.section className="pricingHero" initial={{opacity:0,y:22}} animate={{opacity:1,y:0}}><span>PRICING / BUILT TO SCALE</span><h1>Start exploring.<br/><em>Scale when it matters.</em></h1><p>Choose the SallyIP workspace that fits your research today. Upgrade as your sources, conversations, and team grow.</p></motion.section><section className="pricingGrid">{plans.map((plan,index)=><motion.article className={`pricingCard ${plan.featured?'featured':''} ${plan.university?'university':''}`} initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.08*index}} key={plan.name}>{plan.featured&&<div className="popular"><Sparkles/> MOST POPULAR</div>}<div className="planHead">{plan.university&&<GraduationCap/>}<span>0{index+1}</span><h2>{plan.name}</h2><p>{plan.note}</p></div><div className="planPrice"><strong>{plan.price}</strong>{plan.price!=='Free'&&<span>/ month</span>}</div><ul>{plan.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><button onClick={plan.university?()=>location.href='mailto:team@sallyip.com?subject=SallyIP University Plan':onChat}>{plan.cta}<ArrowRight/></button></motion.article>)}</section><section className="pricingNote"><div><span>NO SURPRISES</span><h2>Research infrastructure,<br/>without infrastructure pricing.</h2></div><p>All paid plans include secure conversations, transparent model identity, private-by-default research sessions, and rights-cleared knowledge retrieval.</p></section></main></div>}
