import {useEffect,useState} from 'react'
import {AlertTriangle,Check,GitCompareArrows,History,Plus,ShieldCheck,X} from 'lucide-react'

const blankEvent={event_type:'office_action',event_date:'',title:'',content:'',claim_number:'',prior_claim_text:'',amended_claim_text:'',source_basis:'user_supplied'}
const label=value=>String(value||'').replaceAll('_',' ')

export default function ProsecutionHistoryWorkspace({matterId,onResult}){
  const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[patents,setPatents]=useState([]),[selected,setSelected]=useState(''),[history,setHistory]=useState(null),[adding,setAdding]=useState(false),[event,setEvent]=useState(blankEvent)
  useEffect(()=>{if(!open||!matterId)return;setBusy(true);fetch(`/api/ip-graph?matter_id=${encodeURIComponent(matterId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Patent list could not be loaded');const items=(data.entities||[]).filter(item=>item.entity_type==='patent');setPatents(items);if(!selected&&items[0])setSelected(items[0].id)}).catch(err=>setError(err.message)).finally(()=>setBusy(false))},[open,matterId])
  useEffect(()=>{if(open&&selected)load(selected)},[selected,open])
  const call=async body=>{const response=await fetch('/api/ip-specialists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({matter_id:matterId,...body})}),data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Prosecution history operation failed');return data}
  const load=async patentId=>{setBusy(true);setError('');try{setHistory(await call({action:'get_prosecution_history',patent_entity_id:patentId}))}catch(err){setError(err.message)}finally{setBusy(false)}}
  const add=async submitEvent=>{submitEvent.preventDefault();setBusy(true);setError('');try{const data=await call({action:'analyze_prosecution_history',patent_entity_id:selected,events:[{...event,sequence:(history?.events?.length||0)+1,claim_number:Number(event.claim_number)||null}]});setHistory(data);setEvent(blankEvent);setAdding(false);const latest=data.events[data.events.length-1];onResult(`## Prosecution history updated\n\n**${data.patent.canonical_identifier||data.patent.name}** now has ${data.events.length} structured prosecution events. Added **${latest.title}** with source basis \`${latest.source_basis}\`. ${latest.scope_signal&&latest.scope_signal!=='no_material_text_change'?`Amendment screen: **${label(latest.scope_signal)}**; jurisdiction-specific legal review remains required.`:''}`,{task_class:'PATENT_PROSECUTION_HISTORY',specialists:['Sally Patents','Sally Claim Interpretation','Sally Evidence','Sally Verification'],source_basis:latest.source_basis})}catch(err){setError(err.message)}finally{setBusy(false)}}
  const review=async item=>{setBusy(true);setError('');try{setHistory(await call({action:'review_prosecution_event',event_id:item.id,review_status:item.review_status,review_note:item.review_note}))}catch(err){setError(err.message)}finally{setBusy(false)}}
  const change=(id,key,value)=>setHistory(current=>({...current,events:current.events.map(item=>item.id===id?{...item,[key]:value}:item)}))
  const close=()=>{setOpen(false);setError('');setAdding(false)}
  return <><div className="prosecutionLaunch"><button onClick={()=>setOpen(true)}><History/>Prosecution history</button></div>{open&&<div className="ipToolOverlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="ipToolModal prosecutionModal"><header><div><span>SALLY PATENTS / PROSECUTION / VERIFICATION</span><h2>{history?history.patent.canonical_identifier||history.patent.name:'Build a prosecution timeline'}</h2></div><button onClick={close}><X/></button></header>{!matterId?<div className="ipToolError">Select or create a matter first.</div>:<><label>Patent<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a patent</option>{patents.map(item=><option value={item.id} key={item.id}>{item.canonical_identifier||item.name}</option>)}</select></label>{history&&<><div className="prosecutionSummary"><article><span>EVENTS</span><strong>{history.events.length}</strong></article><article><span>UNREVIEWED</span><strong>{history.gaps.unreviewed_events}</strong></article><article><span>NO PINPOINT SOURCE</span><strong>{history.gaps.unsourced_events}</strong></article><article><span>UNDATED</span><strong>{history.gaps.undated_events}</strong></article></div><div className="prosecutionActions"><button onClick={()=>setAdding(value=>!value)}><Plus/>Add prosecution event</button></div>{adding&&<EventForm event={event} setEvent={setEvent} add={add} busy={busy}/>}<div className="prosecutionTimeline">{history.events.map(item=><TimelineEvent key={item.id} item={item} busy={busy} change={change} review={review}/>)}{!history.events.length&&!adding&&<div className="claimChartEmpty">No prosecution events recorded for this patent.</div>}</div></>}{!patents.length&&!busy&&<div className="claimChartEmpty">Parse or create a patent entity first.</div>}</>}{error&&<div className="ipToolError">{error}</div>}</section></div>}</>
}

function EventForm({event,setEvent,add,busy}){const amendment=event.event_type==='claim_amendment';return <form className="prosecutionForm" onSubmit={add}><div className="ipToolGrid"><label>Event type<select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}>{['filing','office_action','examiner_objection','applicant_response','argument','claim_amendment','interview','allowance','grant','appeal','opposition','other'].map(value=><option value={value} key={value}>{label(value)}</option>)}</select></label><label>Event date<input type="date" value={event.event_date} onChange={e=>setEvent({...event,event_date:e.target.value})}/></label></div><label>Title<input required value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/></label><label>Event summary<textarea value={event.content} onChange={e=>setEvent({...event,content:e.target.value})}/></label>{amendment&&<><label>Claim number<input type="number" min="1" value={event.claim_number} onChange={e=>setEvent({...event,claim_number:e.target.value})}/></label><div className="prosecutionClaims"><label>Prior claim text<textarea required value={event.prior_claim_text} onChange={e=>setEvent({...event,prior_claim_text:e.target.value})}/></label><label>Amended claim text<textarea required value={event.amended_claim_text} onChange={e=>setEvent({...event,amended_claim_text:e.target.value})}/></label></div></>}<p className="officialSearchNote">This form records user-supplied information. Attach an ingested source passage through the API before treating an event as sourced or verified.</p><button disabled={busy}>{busy?'Saving…':'Add to timeline'}</button></form>}

function TimelineEvent({item,busy,change,review}){return <article className={item.review_status}><div className="prosecutionRail"><i/><span>{String(item.sequence).padStart(2,'0')}</span></div><div className="prosecutionEvent"><div className="prosecutionEventHead"><div><span>{label(item.event_type)} · {item.source_basis}</span><h3>{item.title}</h3><small>{item.event_date||'Date not recorded'}{item.claim_number?` · claim ${item.claim_number}`:''}</small></div>{item.source_passage_id?<ShieldCheck/>:<AlertTriangle/>}</div>{item.content&&<p>{item.content}</p>}{item.scope_signal&&<div className="amendmentSignal"><GitCompareArrows/><div><b>{label(item.scope_signal)}</b><small>{item.explanation}</small>{item.added_terms?.length>0&&<em>Added: {item.added_terms.join(', ')}</em>}{item.removed_terms?.length>0&&<em>Removed: {item.removed_terms.join(', ')}</em>}</div></div>}<div className="prosecutionReview"><select value={item.review_status} onChange={e=>change(item.id,'review_status',e.target.value)}><option value="unreviewed">Unreviewed</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="needs_research">Needs research</option></select><input value={item.review_note||''} onChange={e=>change(item.id,'review_note',e.target.value)} placeholder="Reviewer note"/><button disabled={busy} onClick={()=>review(item)}><Check/>Save review</button></div></div></article>}

