import {useEffect,useState} from 'react'
import {CheckCircle2,Link2,SearchCheck,ShieldCheck,ShieldQuestion,X} from 'lucide-react'

export default function VerificationDeskWorkspace({matterId,onResult}){
  const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[desk,setDesk]=useState({propositions:[],passages:[]}),[record,setRecord]=useState(null)
  const[form,setForm]=useState({issue:'',proposition:'',jurisdiction:''}),[attach,setAttach]=useState({passage_id:'',support_type:'supports',verification_note:''}),[reviews,setReviews]=useState({}),[contraryChecked,setContraryChecked]=useState(false)
  useEffect(()=>{if(open&&matterId)loadDesk()},[open,matterId])
  const request=async(url,options)=>{const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data?.error?.message||'Verification operation failed');return data}
  const loadDesk=async()=>{setBusy(true);setError('');try{const data=await request(`/api/verification-desk?matter_id=${encodeURIComponent(matterId)}`);setDesk(data);setAttach(current=>({...current,passage_id:current.passage_id||data.passages[0]?.passage_id||''}))}catch(err){setError(err.message)}finally{setBusy(false)}}
  const load=async id=>{setBusy(true);setError('');try{const data=await request(`/api/verification-desk?proposition_id=${encodeURIComponent(id)}`);setRecord(data);setContraryChecked(data.proposition.contrary_authority_checked)}catch(err){setError(err.message)}finally{setBusy(false)}}
  const act=async body=>{setBusy(true);setError('');try{const data=await request('/api/verification-desk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(data.proposition)setRecord(data);return data}catch(err){setError(err.message)}finally{setBusy(false)}}
  const create=async event=>{event.preventDefault();const data=await act({action:'create',matter_id:matterId,...form});if(data)onResult(`## Verification record opened\n\nSally will test the proposition **“${data.proposition.proposition}”** at passage level. Its status begins as **pending / insufficient** until supporting authority, source checks, and contrary-authority review are recorded.`,{task_class:'AUTHORITY_VERIFICATION',specialists:['Sally Verification','Sally Citation','Sally Research'],source_basis:'user_supplied'})}
  const attachSource=async event=>{event.preventDefault();const data=await act({action:'attach_source',proposition_id:record.proposition.id,...attach});if(data)setAttach({...attach,verification_note:''})}
  const reviewDraft=source=>reviews[source.source_id]||{existence_confirmed:Boolean(source.verification_review?.existence_confirmed),pinpoint_confirmed:Boolean(source.verification_review?.pinpoint_confirmed),current_status_checked:Boolean(source.verification_review?.current_status_checked),verification_method:source.verification_review?.verification_method||'manual_review',note:source.verification_review?.note||''}
  const updateReview=(source,key,value)=>setReviews(current=>({...current,[source.source_id]:{...reviewDraft(source),...current[source.source_id],[key]:value}}))
  const verifySource=async source=>{const result=await act({action:'review_source',source_id:source.source_id,...reviewDraft(source),...reviews[source.source_id]});if(result)await load(record.proposition.id)}
  const evaluate=async()=>{const data=await act({action:'evaluate',proposition_id:record.proposition.id,contrary_authority_checked:contraryChecked});if(data)onResult(`## Proposition verification updated\n\n**${data.proposition.verification_status} / ${data.proposition.confidence} confidence**\n\nSupporting passages: ${data.assessment.counts.supporting}; verified supporting passages: ${data.assessment.counts.verified_supporting}; contrary passages: ${data.assessment.counts.contrary}. Remaining gaps: ${data.assessment.gaps.join(', ')||'none recorded'}.`,{task_class:'AUTHORITY_VERIFICATION',specialists:['Sally Verification','Sally Citation'],source_basis:'retrieved_source'})}
  const close=()=>{setOpen(false);setRecord(null);setError('')}

  return <><div className="verificationLaunch"><button onClick={()=>setOpen(true)}><SearchCheck/>Verification desk</button></div>{open&&<div className="ipToolOverlay" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="ipToolModal verificationModal"><header><div><span>SALLY VERIFICATION / CITATION</span><h2>{record?'Proposition evidence':'Open a verification record'}</h2></div><button type="button" onClick={close}><X/></button></header>{!matterId?<div className="ipToolError">Select or create a matter first.</div>:record?<RecordView record={record} desk={desk} attach={attach} setAttach={setAttach} attachSource={attachSource} reviews={reviews} reviewDraft={reviewDraft} updateReview={updateReview} verifySource={verifySource} contraryChecked={contraryChecked} setContraryChecked={setContraryChecked} evaluate={evaluate} busy={busy}/>:<CreateView form={form} setForm={setForm} create={create} propositions={desk.propositions} load={load} busy={busy}/>} {error&&<div className="ipToolError">{error}</div>}</section></div>}</>
}

function CreateView({form,setForm,create,propositions,load,busy}){return <form onSubmit={create}><div className="ipToolGrid"><label>Legal issue<input value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})} placeholder="Inventive step / likelihood of confusion"/></label><label>Jurisdiction<input value={form.jurisdiction} onChange={e=>setForm({...form,jurisdiction:e.target.value})}/></label></div><label>Material legal proposition<textarea required value={form.proposition} onChange={e=>setForm({...form,proposition:e.target.value})} placeholder="State one proposition that can be tested against authority."/></label>{propositions.length>0&&<label>Or reopen a proposition<select defaultValue="" onChange={e=>e.target.value&&load(e.target.value)}><option value="">Select proposition</option>{propositions.map(item=><option key={item.id} value={item.id}>{item.proposition.slice(0,100)} · {item.verification_status}</option>)}</select></label>}<p className="officialSearchNote">Each record tests one material proposition. Source existence, pinpoint accuracy, current status, and contrary authority are tracked separately.</p><footer><span><ShieldCheck/>Audited verification history</span><button disabled={busy}>{busy?'Opening…':'Open verification'}</button></footer></form>}

function RecordView({record,desk,attach,setAttach,attachSource,reviews,reviewDraft,updateReview,verifySource,contraryChecked,setContraryChecked,evaluate,busy}){return <><div className="propositionHeader"><div><span>{record.proposition.issue||'LEGAL PROPOSITION'} · {record.proposition.jurisdiction||'jurisdiction unresolved'}</span><h3>{record.proposition.proposition}</h3></div><article className={`confidence-${record.proposition.confidence}`}><strong>{record.proposition.confidence}</strong><small>{record.proposition.verification_status}</small></article></div><div className="verificationCounts"><span>{record.assessment.counts.supporting} supporting</span><span>{record.assessment.counts.verified_supporting} verified</span><span>{record.assessment.counts.contrary} contrary</span><span>{record.assessment.counts.distinguishing} distinguishing</span></div>{record.assessment.gaps.length>0&&<div className="verificationGaps"><ShieldQuestion/>{record.assessment.gaps.map(item=><span key={item}>{item.replaceAll('_',' ')}</span>)}</div>}<form className="attachEvidence" onSubmit={attachSource}><label>Passage<select required value={attach.passage_id} onChange={e=>setAttach({...attach,passage_id:e.target.value})}><option value="">Select matter passage</option>{desk.passages.map(item=><option key={item.passage_id} value={item.passage_id}>Tier {item.authority_tier} · {item.title} · {item.locator_type} {item.locator}</option>)}</select></label><label>Relationship<select value={attach.support_type} onChange={e=>setAttach({...attach,support_type:e.target.value})}><option value="supports">Supports</option><option value="contradicts">Contradicts</option><option value="distinguishes">Distinguishes</option><option value="background">Background</option></select></label><label>Verification note<input value={attach.verification_note} onChange={e=>setAttach({...attach,verification_note:e.target.value})}/></label><button disabled={busy||!desk.passages.length}><Link2/>Attach passage</button></form><div className="propositionSources">{record.sources.map(source=><SourceCard key={source.passage_id} source={source} draft={{...reviewDraft(source),...reviews[source.source_id]}} updateReview={updateReview} verifySource={verifySource} busy={busy}/>)}</div><div className="evaluationBar"><label><input type="checkbox" checked={contraryChecked} onChange={e=>setContraryChecked(e.target.checked)}/> Contrary-authority search completed and recorded</label><button disabled={busy} onClick={evaluate}><CheckCircle2/>Evaluate proposition</button></div></>}

function SourceCard({source,draft,updateReview,verifySource,busy}){return <article className={`support-${source.support_type}`}><header><div><span>{source.support_type}</span><h4>{source.title}</h4><small>{source.citation||'No formal citation'} · {source.locator_type} {source.locator} · Tier {source.authority_tier}</small></div>{source.verified_at?<ShieldCheck/>:<ShieldQuestion/>}</header><p>{source.content}</p><div className="sourceChecks"><label><input type="checkbox" checked={draft.existence_confirmed} onChange={e=>updateReview(source,'existence_confirmed',e.target.checked)}/> Authority exists</label><label><input type="checkbox" checked={draft.pinpoint_confirmed} onChange={e=>updateReview(source,'pinpoint_confirmed',e.target.checked)}/> Pinpoint checked</label><label><input type="checkbox" checked={draft.current_status_checked} onChange={e=>updateReview(source,'current_status_checked',e.target.checked)}/> Current status checked</label><select value={draft.verification_method} onChange={e=>updateReview(source,'verification_method',e.target.value)}><option value="manual_review">Manual review</option><option value="official_web">Official web</option><option value="official_database">Official database</option><option value="uploaded_original">Uploaded original</option></select><input value={draft.note} onChange={e=>updateReview(source,'note',e.target.value)} placeholder="Verification method and limits"/><button disabled={busy} onClick={()=>verifySource(source)}><SearchCheck/>Save source review</button></div></article>}
